### ISSUE TITLE
simplify pexp

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/diy-hazelnut#2]
The pexp type is a little strange -- can you explain why this is necessary?

https://github.com/hazelgrove/diy-hazelnut/blob/ddf80388598e9976c4f2b046e9c5e0846d14a213/lib/app.re#L7

**Comment by yottalogical** [comment]
The functions that generate strings of the types (`prec`, `assoc`, `paren`) become a lot simpler when it's just one recursive type, rather than multiple mutually recursive types. Otherwise it would require writing similar functions for each of the four types.
