### ISSUE TITLE
Types should be wrapped in modules

### ISSUE THREAD

**Issue by evanweissburg** [hazelgrove/diy-hazelnut#3]
Per https://github.com/hazelgrove/hazel/wiki/Code-Style-Guide, each type should have its own module, even if it is small.

There are many overlapping type constructors (eg: `Num`) in the same file from different types. This trips up the compiler in odd to predict ways and is confusing when authoring and reading code. Instead, type-directed constructor disambiguation (eg `HTyp.Num`) would be preferred.

**Comment by cyrus-** [comment]
Closed by #8
